### ISSUE TITLE
Compose Up failing for me Ubuntu 22.04 

### ISSUE THREAD

**Issue by yogesh-bansal** [supermodularxyz/grants-etl#10] opened 2023-08-11 06:23 UTC
I am facing this issue while I use the `docker compose up` And I am not sure where I should put the required JDBC drivers if need be

![image](https://github.com/supermodularxyz/grants-etl/assets/8408205/8733609b-1e5c-4b58-9649-9ce02f15747b)

**Comment by DistributedDoge** [comment] 2023-08-11 15:04
Got similar problem here - one of the images fails to start on WSL2 Ubuntu, I don't think root cause are missing plugins but rather `grantsdb` container misbehaving. Here is my partial compose log after mentions of missing plugins:

```
metabase    | 2023-08-11 14:09:07,814 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
metabase    | 2023-08-11 14:09:07,831 INFO db.setup :: Verifying postgres Database Connection ...
grantsdb exited with code 1
grantsdb    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
grantsdb    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
grantsdb    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

Trying to run `grants-db` from docker without compose is giving me, what I think is root cause:

```
WARNING: The requested image's platform (linux/arm64/v8) does not 
match the detected host platform (linux/amd64) and no specific platform was requested

exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

It may be worth a shot to provide `linux/amd64` version of `grants-db` image?

https://hub.docker.com/layers/ghostffcode/grants-db/latest/images/sha256-db254364bc9ab0e8e2e6766eba3428e98b7b76c5c0edb7ead3b561c92b167281?context=explore

**Comment by ghostffcode** [comment] 2023-08-15 03:50
Ended up defaulting the images to `linux/amd64` os-arch in #11, so you shouldn't have any issues once the PR is merged. Tested out the branch on a VPS running Ubuntu 22.04 as well.

**Comment by DistributedDoge** [comment] 2023-08-15 19:41
@ghostffcode Can confirm that newly-built containers work on my machine.

**Comment by ghostffcode** [comment] 2023-08-15 20:15
> @ghostffcode Can confirm that newly-built containers work on my machine.

Thanks for confirming

**Comment by ghostffcode** [comment] 2023-08-16 08:18
Closing this issue now

**Closed by ghostffcode** 2023-08-16 08:18 UTC
